apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ki4g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ki4g
    app.kubernetes.io/part-of: tkrw-pr712-0075-0030-app
  name: devfile-sample-ki4g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ki4g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ki4g
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-ki4g@sha256:95d8ee3fc576a0bc117d3136cf80b93aad4d61169b0f40c6e30b2ae72539b494
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
